spring.application.name=demo
jwt.secret=${JWT_SECRET}
jwt.expiration=500000
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
cors.allowedOrigins=${ALLOWED_ORIGINS}